### ISSUE TITLE
Migration Setup Failure

### ISSUE THREAD

**Issue by N0ne1eft** [SkyMen-Lab/StorageService#20]
Problem when setting up Migration Folder using `dotnet ef migrations add Init`

```
System.IO.FileNotFoundException: Could not load file or assembly 'GameStorageService, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'GameStorageService, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

**Steps to reproduce:**
- `git clone https://github.com/SkyMen-Lab/StorageService.git`
- `dotnet ef migrations add Init --project StorageService`

**Comment by N0ne1eft** [comment]
Renamed https://github.com/SkyMen-Lab/StorageService/pull/21

**Comment by SkymanOne** [comment]
Fixed in https://github.com/SkyMen-Lab/StorageService/pull/21
