### ISSUE TITLE
No verification for RouterIPAddress entry

### ISSUE THREAD

**Issue by N0ne1eft** [SkyMen-Lab/StorageService#5]
The **/api/team/create** method is allowing any string value for routerIPAddress. Although verification can be added in other micro services before http request being sent I suggest adding database side verification would be better.

<img width="1018" alt="CleanShot 2019-12-27 at 05 31 37@2x" src="https://user-images.githubusercontent.com/41369943/71502842-45bed480-286a-11ea-9a0c-574a64ad3bb1.png">

<img width="482" alt="CleanShot 2019-12-27 at 05 33 45@2x" src="https://user-images.githubusercontent.com/41369943/71502876-7999fa00-286a-11ea-89d3-9347863edef3.png">

No error was reported in the database side log
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?', @p2='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Configs" ("ConnectionType", "RouterIpAddress", "RouterPort")
      VALUES (@p0, @p1, @p2)
      RETURNING "Id";
```

**Comment by SkymanOne** [comment]
To be added in future releases or may be replaced with [Message Aggregator](https://www.nimaara.com/cleaner-pub-sub-using-the-event-aggregator-pattern/)

**Comment by SkymanOne** [comment]
To be fixed

**Comment by SkymanOne** [comment]
has been solved in https://github.com/SkyMen-Lab/StorageService/commit/b81a7afd039f04fff853fd5791447c8bbb0ac42f
